name: charm
version: 2.2
summary: charm and charm-tools
description: charmstore-client and charm-tools
confinement: strict

apps:
  charm:
    command: env PREFIX=$SNAP GIT_EXEC_PATH=$SNAP/usr/lib/git-core LC_ALL=C.UTF-8 $SNAP/bin/charm
    plugs: [network, network-bind, home]
parts:
  charm:
    plugin: godeps
    go-importpath: github.com/juju/charmstore-client
    source: https://github.com/juju/charmstore-client.git
    source-tag: 2.2.0
    source-type: git
    build-packages:
      - bzr
  charm-terms:
    plugin: godeps
    go-importpath: github.com/juju/terms-client
    source: https://github.com/juju/terms-client.git
    source-tag: v1.0.1
    source-type: git
  charm-tools:
    plugin: python
    source: https://github.com/juju/charm-tools.git
    python-version: python2
    source-branch: "2.1"
    build-packages:
      - build-essential
    python-packages:
      - simplejson
      - launchpadlib
    stage-packages:
      - bzr
      - mercurial
      - python-apt
    stage:
      - -bin/virtualenv
  virtualenv:
    plugin: python
    python-version: python3
    python-packages:
      - virtualenv
  git:
    plugin: nil
    stage-packages:
      - git
    snap:
      - -lib/*/libcrypto.so*
      - -lib/*/libssl.so*
      - usr/bin/git*
      - usr/lib/git*
      - usr/lib/*/libasn1.so*
      - usr/lib/*/libcurl-gnutls.so*
      - usr/lib/*/libffi.so*
      - usr/lib/*/libgmp.so*
      - usr/lib/*/libgnutls.so*
      - usr/lib/*/libgssapi.so*
      - usr/lib/*/libgssapi_krb5.so*
      - usr/lib/*/libhcrypto.so*
      - usr/lib/*/libheimbase.so*
      - usr/lib/*/libheimntlm.so*
      - usr/lib/*/libhogweed.so*
      - usr/lib/*/libhx509.so*
      - usr/lib/*/libidn.so*
      - usr/lib/*/libk5crypto.so*
      - usr/lib/*/libkrb5.so*
      - usr/lib/*/libkrb5support.so*
      - usr/lib/*/liblber-2.4.so*
      - usr/lib/*/libldap_r-2.4.so*
      - usr/lib/*/libnettle.so*
      - usr/lib/*/libp11-kit.so*
      - usr/lib/*/libroken.so*
      - usr/lib/*/librtmp.so*
      - usr/lib/*/libsasl2.so*
      - usr/lib/*/libsqlite3.so*
      - usr/lib/*/libtasn1.so*
      - usr/lib/*/libwind.so*
      - -usr/lib/*/openssl-1.0.0*
      - -usr/share/doc/libssl1.0.0*
